/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schema": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Schema */
        get: operations["schema_api_schema_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/doctor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Doctor */
        get: operations["doctor_api_doctor_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Settings */
        get: operations["settings_api_settings_get"];
        /** Save Settings */
        put: operations["save_settings_api_settings_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/providers/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Provider Status */
        get: operations["provider_status_api_providers_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/providers/{name}/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Models */
        get: operations["models_api_providers__name__models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/providers/{name}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Test Provider */
        post: operations["test_provider_api_providers__name__test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/voices/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Voice Preview */
        post: operations["voice_preview_api_voices_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/music": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Music */
        get: operations["music_api_music_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/music/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Music File */
        get: operations["music_file_api_music__name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/briefs/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate */
        post: operations["validate_api_briefs_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/briefs/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Brief */
        post: operations["import_brief_api_briefs_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/briefs/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Export Brief */
        post: operations["export_brief_api_briefs_export_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_api_runs_get"];
        put?: never;
        /** Create Run */
        post: operations["create_run_api_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run */
        get: operations["run_api_runs__run_id__get"];
        put?: never;
        post?: never;
        /** Delete */
        delete: operations["delete_api_runs__run_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start */
        post: operations["start_api_runs__run_id__start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/script/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve Script */
        post: operations["approve_script_api_runs__run_id__script_approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/script/regenerate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Regenerate Script */
        post: operations["regenerate_script_api_runs__run_id__script_regenerate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/script/undo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Undo Script */
        post: operations["undo_script_api_runs__run_id__script_undo_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/spec": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Edit Spec */
        put: operations["edit_spec_api_runs__run_id__spec_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/scenes/{index}/regenerate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Regenerate Scene */
        post: operations["regenerate_scene_api_runs__run_id__scenes__index__regenerate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/scenes/{index}/undo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Undo Scene */
        post: operations["undo_scene_api_runs__run_id__scenes__index__undo_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve Scenes */
        post: operations["approve_scenes_api_runs__run_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel */
        post: operations["cancel_api_runs__run_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume */
        post: operations["resume_api_runs__run_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Events */
        get: operations["events_api_runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/files/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download */
        get: operations["download_api_runs__run_id__files__name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/bundle.zip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Bundle */
        get: operations["bundle_api_runs__run_id__bundle_zip_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/reveal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reveal */
        post: operations["reveal_api_runs__run_id__reveal_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload */
        post: operations["upload_api_uploads_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/capture/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Capture */
        post: operations["capture_api_capture_test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/login/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login Start */
        post: operations["login_start_api_login_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/login/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Login Status */
        get: operations["login_status_api_login_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/login/finish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login Finish */
        post: operations["login_finish_api_login_finish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Beat */
        Beat: {
            /**
             * Role
             * @description What this beat does in the story
             * @enum {string}
             */
            role: "hook" | "problem" | "feature" | "cta";
            /**
             * Narration
             * @description Exactly what the voice says in this beat
             */
            narration: string;
            /**
             * Feature
             * @description For feature beats: the brief feature this beat covers, verbatim
             */
            feature?: string | null;
        };
        /** Body_upload_api_uploads_post */
        Body_upload_api_uploads_post: {
            /** Run Id */
            run_id: string;
            /** File */
            file: string;
            /**
             * Caption
             * @default
             */
            caption: string;
            /**
             * Logo
             * @default false
             */
            logo: boolean;
        };
        /** Brand */
        Brand: {
            /**
             * Colors
             * @description Accent, background, text
             */
            colors?: string[];
            /** Logo */
            logo?: string | null;
        };
        /** Brief */
        Brief: {
            /**
             * Level
             * @default small
             * @enum {string}
             */
            level: "small" | "medium" | "high";
            /** Audience */
            audience: string;
            /** Storyline */
            storyline: string;
            /** Features */
            features: string[];
            /**
             * Duration
             * @default 60
             */
            duration: number;
            /**
             * Format
             * @default 16:9
             * @enum {string}
             */
            format: "16:9" | "9:16" | "1:1";
            /**
             * @default {
             *       "gender": "female",
             *       "accent": "us",
             *       "speed": 1
             *     }
             */
            voice: components["schemas"]["Voice"];
            /** Closing */
            closing: string;
            /**
             * Credit
             * @default end
             * @enum {string}
             */
            credit: "end" | "corner";
            /**
             * Tone
             * @default clear and direct
             */
            tone: string;
            /**
             * Pacing
             * @default balanced
             * @enum {string}
             */
            pacing: "slow" | "balanced" | "fast";
            /**
             * @default {
             *       "colors": []
             *     }
             */
            brand: components["schemas"]["Brand"];
            /**
             * Theme
             * @default default
             * @enum {string}
             */
            theme: "default" | "dark" | "brand";
            /** Music Mood */
            music_mood?: ("calm" | "upbeat" | "tech" | "dramatic" | "inspiring") | null;
            /** Cta Url */
            cta_url?: string | null;
            /**
             * @default {
             *       "source": "auto",
             *       "generate": false
             *     }
             */
            visuals: components["schemas"]["Visuals"];
            /** Scenes */
            scenes?: (components["schemas"]["HookScene"] | components["schemas"]["FeatureCardScene"] | components["schemas"]["CtaScene"] | components["schemas"]["ImageScene"] | components["schemas"]["ScreenshotScene"] | components["schemas"]["ProblemScene"] | components["schemas"]["StatScene"] | components["schemas"]["BulletsScene"])[] | null;
            /** Music Track */
            music_track?: string | null;
            /**
             * Music Volume
             * @default 0.3
             */
            music_volume: number;
        };
        /** BulletsScene */
        BulletsScene: {
            /** Index */
            index: number;
            /** Narration */
            narration: string;
            /** Feature */
            feature?: string | null;
            /** Duration Override */
            duration_override?: number | null;
            voice_override?: components["schemas"]["Voice"] | null;
            /**
             * Image Approved
             * @default false
             */
            image_approved: boolean;
            /**
             * @default {
             *       "kind": "none"
             *     }
             */
            visual_request: components["schemas"]["VisualRequest"];
            visual?: components["schemas"]["VisualAsset"] | null;
            /**
             * Audio
             * @description Narration WAV, relative to the run folder
             */
            audio?: string | null;
            /**
             * Start
             * @default 0
             */
            start: number;
            /**
             * Duration
             * @default 0
             */
            duration: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            template: "bullets";
            text: components["schemas"]["BulletsText"];
        };
        /** BulletsText */
        BulletsText: {
            /** Headline */
            headline: string;
            /** Items */
            items: string[];
        };
        /** CaptureRequest */
        CaptureRequest: {
            /** Run Id */
            run_id: string;
            screenshots: components["schemas"]["Screenshots"];
            /**
             * Format
             * @enum {string}
             */
            format: "16:9" | "9:16" | "1:1";
        };
        /** Config */
        Config: {
            /**
             * Provider
             * @default claude
             * @enum {string}
             */
            provider: "claude" | "bedrock" | "openai" | "ollama" | "copilot";
            /** Models */
            models?: {
                [key: string]: components["schemas"]["Tiers"];
            };
            /** Nodes */
            nodes?: {
                [key: string]: "claude" | "bedrock" | "openai" | "ollama" | "copilot";
            };
            /** Tier Providers */
            tier_providers?: {
                [key: string]: "claude" | "bedrock" | "openai" | "ollama" | "copilot";
            };
            /**
             * @default {
             *       "level": "small",
             *       "format": "16:9",
             *       "voice": {
             *         "accent": "us",
             *         "gender": "female",
             *         "speed": 1
             *       },
             *       "credit": "end"
             *     }
             */
            defaults: components["schemas"]["Defaults"];
            /**
             * Ollama Host
             * @default http://localhost:11434
             */
            ollama_host: string;
            image_generation?: components["schemas"]["ImageGeneration"] | null;
            /**
             * Max Tokens
             * @default 8000
             */
            max_tokens: number;
            /**
             * Runs Dir
             * Format: path
             * @default runs
             */
            runs_dir: string;
        };
        /** CreateRun */
        CreateRun: {
            brief: components["schemas"]["Brief"];
            /**
             * Start
             * @default true
             */
            start: boolean;
        };
        /** Credit */
        Credit: {
            /**
             * Mode
             * @enum {string}
             */
            mode: "end" | "corner";
            /**
             * Text
             * @default Made with ReelHive by Mr.D
             */
            text: string;
            /**
             * Duration
             * @description Seconds the end card takes; 0 for corner
             */
            duration: number;
        };
        /** CtaScene */
        CtaScene: {
            /** Index */
            index: number;
            /** Narration */
            narration: string;
            /** Feature */
            feature?: string | null;
            /** Duration Override */
            duration_override?: number | null;
            voice_override?: components["schemas"]["Voice"] | null;
            /**
             * Image Approved
             * @default false
             */
            image_approved: boolean;
            /**
             * @default {
             *       "kind": "none"
             *     }
             */
            visual_request: components["schemas"]["VisualRequest"];
            visual?: components["schemas"]["VisualAsset"] | null;
            /**
             * Audio
             * @description Narration WAV, relative to the run folder
             */
            audio?: string | null;
            /**
             * Start
             * @default 0
             */
            start: number;
            /**
             * Duration
             * @default 0
             */
            duration: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            template: "cta";
            text: components["schemas"]["CtaText"];
        };
        /** CtaText */
        CtaText: {
            /** Headline */
            headline: string;
            /** Subline */
            subline?: string | null;
        };
        /** Defaults */
        Defaults: {
            /**
             * Level
             * @default small
             * @enum {string}
             */
            level: "small" | "medium" | "high";
            /**
             * Format
             * @default 16:9
             * @enum {string}
             */
            format: "16:9" | "9:16" | "1:1";
            /**
             * @default {
             *       "gender": "female",
             *       "accent": "us",
             *       "speed": 1
             *     }
             */
            voice: components["schemas"]["Voice"];
            /** Music Mood */
            music_mood?: ("calm" | "upbeat" | "tech" | "dramatic" | "inspiring") | null;
            /**
             * Credit
             * @default end
             * @enum {string}
             */
            credit: "end" | "corner";
        };
        /** FeatureCardScene */
        FeatureCardScene: {
            /** Index */
            index: number;
            /** Narration */
            narration: string;
            /** Feature */
            feature?: string | null;
            /** Duration Override */
            duration_override?: number | null;
            voice_override?: components["schemas"]["Voice"] | null;
            /**
             * Image Approved
             * @default false
             */
            image_approved: boolean;
            /**
             * @default {
             *       "kind": "none"
             *     }
             */
            visual_request: components["schemas"]["VisualRequest"];
            visual?: components["schemas"]["VisualAsset"] | null;
            /**
             * Audio
             * @description Narration WAV, relative to the run folder
             */
            audio?: string | null;
            /**
             * Start
             * @default 0
             */
            start: number;
            /**
             * Duration
             * @default 0
             */
            duration: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            template: "feature-card";
            text: components["schemas"]["FeatureCardText"];
        };
        /** FeatureCardText */
        FeatureCardText: {
            /**
             * Label
             * @description Short marker such as 01
             */
            label?: string | null;
            /** Headline */
            headline: string;
            /** Body */
            body?: string | null;
        };
        /** Generate */
        Generate: {
            /**
             * Provider
             * @default openai
             * @constant
             */
            provider: "openai";
            /**
             * Style
             * @default
             */
            style: string;
            /**
             * Max Images
             * @default 6
             */
            max_images: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HookScene */
        HookScene: {
            /** Index */
            index: number;
            /** Narration */
            narration: string;
            /** Feature */
            feature?: string | null;
            /** Duration Override */
            duration_override?: number | null;
            voice_override?: components["schemas"]["Voice"] | null;
            /**
             * Image Approved
             * @default false
             */
            image_approved: boolean;
            /**
             * @default {
             *       "kind": "none"
             *     }
             */
            visual_request: components["schemas"]["VisualRequest"];
            visual?: components["schemas"]["VisualAsset"] | null;
            /**
             * Audio
             * @description Narration WAV, relative to the run folder
             */
            audio?: string | null;
            /**
             * Start
             * @default 0
             */
            start: number;
            /**
             * Duration
             * @default 0
             */
            duration: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            template: "hook";
            text: components["schemas"]["HookText"];
        };
        /** HookText */
        HookText: {
            /** Headline */
            headline: string;
            /** Subline */
            subline?: string | null;
        };
        /** ImageGeneration */
        ImageGeneration: {
            /** Model */
            model: string;
            /**
             * Cost Per Image
             * @description Optional USD estimate from your pricing
             */
            cost_per_image?: number | null;
        };
        /** ImageScene */
        ImageScene: {
            /** Index */
            index: number;
            /** Narration */
            narration: string;
            /** Feature */
            feature?: string | null;
            /** Duration Override */
            duration_override?: number | null;
            voice_override?: components["schemas"]["Voice"] | null;
            /**
             * Image Approved
             * @default false
             */
            image_approved: boolean;
            /**
             * @default {
             *       "kind": "none"
             *     }
             */
            visual_request: components["schemas"]["VisualRequest"];
            visual?: components["schemas"]["VisualAsset"] | null;
            /**
             * Audio
             * @description Narration WAV, relative to the run folder
             */
            audio?: string | null;
            /**
             * Start
             * @default 0
             */
            start: number;
            /**
             * Duration
             * @default 0
             */
            duration: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            template: "image-full";
            text: components["schemas"]["HookText"];
        };
        /** Images */
        Images: {
            /** Dir */
            dir: string;
            /** Captions */
            captions?: string | null;
            /**
             * Describe Images
             * @default false
             */
            describe_images: boolean;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Run Id */
            run_id: string;
            /** Url */
            url: string;
        };
        /** Note */
        Note: {
            /**
             * Note
             * @default
             */
            note: string;
            /**
             * Suggestion
             * @description Label of the quick action being applied
             */
            suggestion?: string | null;
            /**
             * Beat
             * @description Beat the note is about (script quick actions)
             */
            beat?: number | null;
        };
        /** ProblemScene */
        ProblemScene: {
            /** Index */
            index: number;
            /** Narration */
            narration: string;
            /** Feature */
            feature?: string | null;
            /** Duration Override */
            duration_override?: number | null;
            voice_override?: components["schemas"]["Voice"] | null;
            /**
             * Image Approved
             * @default false
             */
            image_approved: boolean;
            /**
             * @default {
             *       "kind": "none"
             *     }
             */
            visual_request: components["schemas"]["VisualRequest"];
            visual?: components["schemas"]["VisualAsset"] | null;
            /**
             * Audio
             * @description Narration WAV, relative to the run folder
             */
            audio?: string | null;
            /**
             * Start
             * @default 0
             */
            start: number;
            /**
             * Duration
             * @default 0
             */
            duration: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            template: "problem";
            text: components["schemas"]["HookText"];
        };
        /** RunView */
        RunView: {
            /** Id */
            id: string;
            /** Status */
            status: string;
            brief?: components["schemas"]["Brief"] | null;
            script?: components["schemas"]["Script"] | null;
            spec?: components["schemas"]["SceneSpec"] | null;
            /**
             * Provider
             * @default claude
             */
            provider: string;
            /**
             * Report
             * @default []
             */
            report: string[];
            /** Queue Position */
            queue_position?: number | null;
            /**
             * Video
             * @default false
             */
            video: boolean;
        };
        /** SceneSpec */
        SceneSpec: {
            /**
             * Version
             * @default 1
             */
            version: number;
            /**
             * Format
             * @default 16:9
             */
            format: string;
            /**
             * Width
             * @default 1920
             */
            width: number;
            /**
             * Height
             * @default 1080
             */
            height: number;
            /**
             * Fps
             * @default 30
             */
            fps: number;
            /**
             * Duration
             * @default 0
             */
            duration: number;
            /**
             * @default {
             *       "background": "#0f1115",
             *       "surface": "#1a1d24",
             *       "text": "#f5f5f4",
             *       "muted": "#a8a29e",
             *       "accent": "#f5a524"
             *     }
             */
            theme: components["schemas"]["Theme"];
            /** Scenes */
            scenes: (components["schemas"]["HookScene"] | components["schemas"]["FeatureCardScene"] | components["schemas"]["CtaScene"] | components["schemas"]["ImageScene"] | components["schemas"]["ScreenshotScene"] | components["schemas"]["ProblemScene"] | components["schemas"]["StatScene"] | components["schemas"]["BulletsScene"])[];
            credit?: components["schemas"]["Credit"] | null;
            /**
             * Music Volume
             * @default 0.3
             */
            music_volume: number;
            /**
             * Music
             * @description Music file chosen from the library
             */
            music?: string | null;
        };
        /** ScreenshotScene */
        ScreenshotScene: {
            /** Index */
            index: number;
            /** Narration */
            narration: string;
            /** Feature */
            feature?: string | null;
            /** Duration Override */
            duration_override?: number | null;
            voice_override?: components["schemas"]["Voice"] | null;
            /**
             * Image Approved
             * @default false
             */
            image_approved: boolean;
            /**
             * @default {
             *       "kind": "none"
             *     }
             */
            visual_request: components["schemas"]["VisualRequest"];
            visual?: components["schemas"]["VisualAsset"] | null;
            /**
             * Audio
             * @description Narration WAV, relative to the run folder
             */
            audio?: string | null;
            /**
             * Start
             * @default 0
             */
            start: number;
            /**
             * Duration
             * @default 0
             */
            duration: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            template: "screenshot-pan";
            text: components["schemas"]["HookText"];
        };
        /** Screenshots */
        Screenshots: {
            /** Url */
            url: string;
            /** Routes */
            routes?: string[];
            /** Storage State */
            storage_state?: string | null;
            /** Mask */
            mask?: string[];
            /**
             * Frame
             * @default none
             * @enum {string}
             */
            frame: "browser" | "phone" | "none";
        };
        /** Script */
        Script: {
            /** Title */
            title: string;
            /** Beats */
            beats: components["schemas"]["Beat"][];
        };
        /** StatScene */
        StatScene: {
            /** Index */
            index: number;
            /** Narration */
            narration: string;
            /** Feature */
            feature?: string | null;
            /** Duration Override */
            duration_override?: number | null;
            voice_override?: components["schemas"]["Voice"] | null;
            /**
             * Image Approved
             * @default false
             */
            image_approved: boolean;
            /**
             * @default {
             *       "kind": "none"
             *     }
             */
            visual_request: components["schemas"]["VisualRequest"];
            visual?: components["schemas"]["VisualAsset"] | null;
            /**
             * Audio
             * @description Narration WAV, relative to the run folder
             */
            audio?: string | null;
            /**
             * Start
             * @default 0
             */
            start: number;
            /**
             * Duration
             * @default 0
             */
            duration: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            template: "stat";
            text: components["schemas"]["StatText"];
        };
        /** StatText */
        StatText: {
            /** Headline */
            headline: string;
            /** Subline */
            subline?: string | null;
        };
        /** Theme */
        Theme: {
            /**
             * Background
             * @default #0f1115
             */
            background: string;
            /**
             * Surface
             * @default #1a1d24
             */
            surface: string;
            /**
             * Text
             * @default #f5f5f4
             */
            text: string;
            /**
             * Muted
             * @default #a8a29e
             */
            muted: string;
            /**
             * Accent
             * @default #f5a524
             */
            accent: string;
            /** Logo */
            logo?: string | null;
        };
        /** Tiers */
        Tiers: {
            /** Strong */
            strong: string;
            /** Fast */
            fast: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VisualAsset */
        VisualAsset: {
            /**
             * Source
             * @enum {string}
             */
            source: "provided" | "screenshot" | "generated";
            /** File */
            file: string;
            /**
             * Frame
             * @default none
             * @enum {string}
             */
            frame: "browser" | "phone" | "none";
        };
        /** VisualRequest */
        VisualRequest: {
            /**
             * Kind
             * @default none
             * @enum {string}
             */
            kind: "product_ui" | "concept" | "none";
            /**
             * Image
             * @description Filename from the provided image catalog
             */
            image?: string | null;
            /**
             * Route
             * @description Route from the screenshot catalog
             */
            route?: string | null;
            /**
             * Prompt
             * @description Concept illustration only; never product UI
             */
            prompt?: string | null;
        };
        /** Visuals */
        Visuals: {
            /**
             * Source
             * @default auto
             * @enum {string}
             */
            source: "auto" | "screenshots" | "images" | "generate" | "none";
            /** Url */
            url?: string | null;
            screenshots?: components["schemas"]["Screenshots"] | null;
            /** Images */
            images?: components["schemas"]["Images"] | string | null;
            /**
             * Generate
             * @default false
             */
            generate: components["schemas"]["Generate"] | boolean;
        };
        /** Voice */
        Voice: {
            /**
             * Gender
             * @default female
             * @enum {string}
             */
            gender: "female" | "male";
            /**
             * Accent
             * @default us
             * @enum {string}
             */
            accent: "us" | "uk";
            /**
             * Speed
             * @default 1
             */
            speed: number;
        };
        /** YamlBrief */
        YamlBrief: {
            /** Text */
            text: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    schema_api_schema_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    doctor_api_doctor_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    settings_api_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Config"];
                };
            };
        };
    };
    save_settings_api_settings_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Config"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Config"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    provider_status_api_providers_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    models_api_providers__name__models_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_provider_api_providers__name__test_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    voice_preview_api_voices_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Voice"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    music_api_music_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    music_file_api_music__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_api_briefs_validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Brief"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Brief"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_brief_api_briefs_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["YamlBrief"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Brief"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_brief_api_briefs_export_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Brief"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_api_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunView"][];
                };
            };
        };
    };
    create_run_api_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRun"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_api_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_api_runs__run_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_api_runs__run_id__start_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Brief"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_script_api_runs__run_id__script_approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Script"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    regenerate_script_api_runs__run_id__script_regenerate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Note"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    undo_script_api_runs__run_id__script_undo_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_spec_api_runs__run_id__spec_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SceneSpec"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    regenerate_scene_api_runs__run_id__scenes__index__regenerate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                index: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Note"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    undo_scene_api_runs__run_id__scenes__index__undo_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                index: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_scenes_api_runs__run_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_api_runs__run_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_api_runs__run_id__resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    events_api_runs__run_id__events_get: {
        parameters: {
            query?: {
                after?: number;
                follow?: boolean;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_api_runs__run_id__files__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bundle_api_runs__run_id__bundle_zip_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reveal_api_runs__run_id__reveal_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_api_uploads_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_api_uploads_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    capture_api_capture_test_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CaptureRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_start_api_login_start_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_status_api_login_status_get: {
        parameters: {
            query: {
                id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_finish_api_login_finish_post: {
        parameters: {
            query: {
                id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
