import {useEffect, useState} from 'react';
import {useForm} from 'react-hook-form';
import {zodResolver} from '@hookform/resolvers/zod';
import {useNavigate} from 'react-router-dom';
import {useQuery} from '@tanstack/react-query';
import {ArrowRight, ArrowUp, ArrowDown, Plus, Upload, X, Play} from 'lucide-react';
import {briefSchema} from '../schemas/brief';
import {request, download, fileUrl, type Brief, type Run, type Config} from '../api/client';
import {Field, ErrorNote, VoiceFields} from '../components/common';
const initial: Brief = {level:'medium',audience:'',storyline:'',features:[''],duration:60,format:'16:9',voice:{gender:'female',accent:'us',speed:1},closing:'',credit:'end',tone:'clear and direct',pacing:'balanced',brand:{colors:[]},theme:'default',music_mood:'tech',visuals:{source:'none',generate:false},music_volume:0.3};
function savedDraft(): Brief {
 try { return JSON.parse(localStorage.getItem('reelhive-draft') || 'null') || initial; }
 catch { localStorage.removeItem('reelhive-draft'); return initial; }
}
export function BriefPage() {
 const navigate=useNavigate();
 const [error,setError]=useState<unknown>(); const [busy,setBusy]=useState(false);const [step,setStep]=useState(0);const [runId,setRunId]=useState('');const [previews,setPreviews]=useState<string[]>([]);const [login,setLogin]=useState('');const [caption,setCaption]=useState('');
 const {register,watch,setValue,reset,handleSubmit,formState:{errors}}=useForm<Brief>({defaultValues:savedDraft(),resolver:zodResolver(briefSchema) as any,mode:'onChange'});
 const brief=watch();const advanced=brief.level!=='small';
 const settings=useQuery({queryKey:['settings'],queryFn:()=>request<Config>('/settings')});
 const providers=useQuery({queryKey:['providers'],queryFn:()=>request<Record<string,any>>('/providers/status')});
 const health=useQuery({queryKey:['health'],queryFn:()=>request<{credit_disabled:boolean}>('/health')});
 const music=useQuery({queryKey:['music'],queryFn:()=>request<{file:string;mood:string;title?:string}[]>('/music')});
 useEffect(()=>{if(settings.data&&!localStorage.getItem('reelhive-draft'))reset({...initial,...settings.data.defaults});},[settings.data,reset]);
 useEffect(()=>{const sub=watch(value=>localStorage.setItem('reelhive-draft',JSON.stringify(value)));return()=>sub.unsubscribe();},[watch]);
 const operation=async(fn:()=>Promise<void>)=>{setBusy(true);setError(null);try{await fn();}catch(e){setError(e);}finally{setBusy(false);}};
 const ensureRun=async()=>{if(runId)return runId;const r=await request<Run>('/runs','POST',{brief:briefSchema.parse(brief),start:false});setRunId(r.id);return r.id;};
 const start=handleSubmit(value=>operation(async()=>{const r=runId?await request<Run>(`/runs/${runId}/start`,'POST',value).then(()=>({id:runId})):await request<Run>('/runs','POST',{brief:value});localStorage.removeItem('reelhive-draft');navigate(`/runs/${r.id}`);}));
 const upload=async(files:FileList|null,logo=false)=>operation(async()=>{if(!files)return;const id=await ensureRun();for(const file of Array.from(files)){const data=new FormData();data.append('run_id',id);data.append('file',file);data.append('caption',caption);data.append('logo',String(logo));const result=await request<{brief:Brief;name:string}>('/uploads','POST',data);setValue(logo?'brand':'visuals',logo?{...brief.brand,logo:result.brief.brand?.logo}:{...brief.visuals,images:result.brief.visuals?.images});if(!logo)setPreviews(v=>[...v,`uploads/${result.name}`]);}});
 const visuals=brief.visuals||{source:'none'};
 const setVisual=(patch:Partial<NonNullable<Brief['visuals']>>)=>setValue('visuals',{...visuals,...patch});
 const screenshots=typeof visuals.screenshots==='object'&&visuals.screenshots?visuals.screenshots:{url:'',routes:[],mask:[],frame:'browser' as const};
 const shot=(patch:object)=>setVisual({screenshots:{...screenshots,...patch}});
 return <><div className="page-heading"><div><div className="eyebrow">NEW PRODUCTION</div><h1>Make your next video.</h1><p>A brief, your voice, and a story worth showing.</p></div><div className="toolbar"><label className="button secondary"><Upload size={16}/>Load brief<input type="file" accept=".yaml,.yml" hidden onChange={e=>operation(async()=>{const f=e.target.files?.[0];if(f){reset(await request<Brief>('/briefs/import','POST',{text:await f.text()}));setRunId('');}})}/></label><button className="secondary" onClick={()=>operation(async()=>download(await request<Blob>('/briefs/export','POST',brief),'brief.yaml'))}>Export YAML</button></div></div>
 <ol className="stepper"><li className={step===0?'active':''}><button onClick={()=>setStep(0)}>01 Brief</button></li>{advanced&&<li className={step===1?'active':''}><button onClick={handleSubmit(()=>setStep(1))}>02 Visuals</button></li>}<li>{advanced?'03 Script':'02 Run'}</li>{brief.level==='high'&&<li>04 Scenes</li>}{advanced&&<li>{brief.level==='high'?'05':'04'} Run</li>}</ol>
 <ErrorNote error={error}/>{Object.keys(errors).length>0&&<p className="error" role="alert">Check the highlighted fields before continuing.</p>}
 <form onSubmit={start} className="brief-layout"><div className="form-body">
 {step===0&&<><section><div className="section-title"><span>01</span><h2>Your story</h2></div><Field label="Control level"><div className="segments">{(['small','medium','high'] as const).map(level=><button type="button" key={level} aria-pressed={brief.level===level} onClick={()=>setValue('level',level)}><strong>{level[0].toUpperCase()+level.slice(1)}</strong><small>{level==='small'?'Brief to video':level==='medium'?'Review the script':'Direct every scene'}</small></button>)}</div></Field><Field label="Who is this for?"><input {...register('audience')} placeholder="Developers building on AWS" aria-invalid={!!errors.audience}/>{errors.audience&&<small className="error">{errors.audience.message}</small>}</Field><Field label="What’s the story?"><textarea rows={3} {...register('storyline')} placeholder="Start with the problem. Show what changes. Leave them with one clear idea." aria-invalid={!!errors.storyline}/>{errors.storyline&&<small className="error">{errors.storyline.message}</small>}</Field><div className="field"><span>Features to cover</span>{(brief.features||['']).map((f,i)=><div className="feature-row" key={i}><span className="index">{String(i+1).padStart(2,'0')}</span><input aria-label={`Feature ${i+1}`} value={f} onChange={e=>setValue('features',brief.features.map((v,j)=>j===i?e.target.value:v),{shouldValidate:true})}/><button type="button" className="icon" aria-label={`Move feature ${i+1} up`} disabled={i===0} onClick={()=>{const a=[...brief.features];[a[i-1],a[i]]=[a[i],a[i-1]];setValue('features',a);}}><ArrowUp size={16}/></button><button type="button" className="icon" aria-label={`Move feature ${i+1} down`} disabled={i===brief.features.length-1} onClick={()=>{const a=[...brief.features];[a[i+1],a[i]]=[a[i],a[i+1]];setValue('features',a);}}><ArrowDown size={16}/></button><button type="button" className="icon" aria-label={`Remove feature ${i+1}`} disabled={brief.features.length===1} onClick={()=>setValue('features',brief.features.filter((_,j)=>j!==i))}><X size={16}/></button></div>)}<button type="button" className="text-button" disabled={brief.features?.length>=8} onClick={()=>setValue('features',[...brief.features,''])}><Plus size={16}/>Add feature</button></div><Field label="Closing message" hint={`${brief.closing?.length||0}/60 · Must appear exactly in your video`}><input {...register('closing')} maxLength={60} placeholder="Build something that matters." aria-invalid={!!errors.closing}/>{errors.closing&&<small className="error">{errors.closing.message}</small>}</Field></section>
 <section><div className="section-title"><span>02</span><h2>Make it yours</h2></div><div className="row"><Field label={`Duration · ${brief.duration||60}s`}><input type="range" min={15} max={180} {...register('duration',{valueAsNumber:true})}/></Field><Field label="Seconds"><input type="number" min={15} max={180} {...register('duration',{valueAsNumber:true})}/></Field></div><Field label="Format"><div className="segments formats">{(['16:9','9:16','1:1'] as const).map(format=><button type="button" key={format} aria-pressed={brief.format===format} onClick={()=>setValue('format',format)}><span className="format-frame" style={{aspectRatio:format.replace(':','/')}}/>{format}<small>{format==='16:9'?'Landscape':format==='9:16'?'Portrait':'Square'}</small></button>)}</div></Field>{brief.voice&&<VoiceFields value={brief.voice} onChange={value=>setValue('voice',value)}/>}<button type="button" className="text-button" disabled={busy} onClick={()=>operation(async()=>{const b=await request<Blob>('/voices/preview','POST',brief.voice);const u=URL.createObjectURL(b);const a=new Audio(u);a.onended=()=>URL.revokeObjectURL(u);await a.play();})}><Play size={15}/>Preview voice</button>
 {advanced&&<><div className="row"><Field label="Tone"><input {...register('tone')}/></Field><Field label="Pacing"><select {...register('pacing')}><option>slow</option><option>balanced</option><option>fast</option></select></Field></div><div className="row"><Field label="Theme"><select {...register('theme')}><option>default</option><option>dark</option><option>brand</option></select></Field><Field label="CTA URL"><input {...register('cta_url')} placeholder="example.com"/></Field></div><Field label="Brand colors"><div className="row">{['Accent','Background','Text'].map((name,i)=><label key={name}>{name}<input aria-label={name} type="color" value={brief.brand?.colors?.[i]||['#bafa42','#111312','#f5f3eb'][i]} onChange={e=>{const colors=[...(brief.brand?.colors?.length?brief.brand.colors:['#bafa42','#111312','#f5f3eb'])];colors[i]=e.target.value;setValue('brand',{...brief.brand,colors});}}/></label>)}</div></Field><label className="button secondary">Upload logo<input hidden type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>upload(e.target.files,true)}/></label><div className="row"><Field label="Music mood"><select {...register('music_mood')}><option>tech</option><option>calm</option><option>upbeat</option><option>dramatic</option><option>inspiring</option></select></Field><Field label="Music volume"><input type="range" min="0" max="1" step="0.05" {...register('music_volume',{valueAsNumber:true})}/></Field></div>{music.data?.filter(t=>t.mood===brief.music_mood).slice(0,1).map(t=><audio key={t.file} controls aria-label={`${t.mood} music sample`} src={`/api/music/${t.file}?token=${encodeURIComponent(sessionStorage.getItem('reelhive-token')||'')}`}/>)}{brief.level==='high'&&<Field label="Music track"><select {...register('music_track')}><option value="">Let the composer choose</option>{music.data?.map(t=><option key={t.file} value={t.file}>{t.title||t.file}</option>)}</select></Field>}</>}
 {health.data?.credit_disabled?<p className="muted">Credit is off (environment variable).</p>:<Field label="Made with ReelHive credit"><select {...register('credit')}><option value="end">End card</option><option value="corner">Corner</option></select></Field>}</section></>}
 {(step===1||!advanced)&&<section><div className="section-title"><span>{advanced?'02':'03'}</span><h2>Your visuals</h2></div><Field label="Visual source"><select value={visuals.source} onChange={e=>{const source=e.target.value as NonNullable<Brief['visuals']>['source'];setVisual({source,...(source==='screenshots'?{screenshots}:source==='images'?{images:{dir:'',describe_images:false}}:source==='generate'?{generate:{provider:'openai',style:'',max_images:6}}:{})});}}>{['none','auto','screenshots','images','generate'].map(v=><option key={v}>{v}</option>)}</select></Field>{['screenshots','auto'].includes(visuals.source||'')&&<><Field label="App URL"><input type="url" value={screenshots.url} onChange={e=>shot({url:e.target.value})} placeholder="http://localhost:3000"/></Field><Field label="Routes" hint="One per line. Leave empty to discover up to 10 pages."><textarea value={screenshots.routes?.join('\n')} onChange={e=>shot({routes:e.target.value.split('\n').filter(Boolean)})}/></Field><Field label="Mask selectors" hint="One CSS selector per line. Hidden before capture."><textarea value={screenshots.mask?.join('\n')} onChange={e=>shot({mask:e.target.value.split('\n').filter(Boolean)})}/></Field><Field label="Frame"><select value={screenshots.frame} onChange={e=>shot({frame:e.target.value})}><option>browser</option><option>phone</option><option>none</option></select></Field><div className="toolbar"><button type="button" className="secondary" disabled={busy} onClick={()=>operation(async()=>{const id=await ensureRun();const result=await request<{id:string}>('/login/start','POST',{run_id:id,url:screenshots.url});setLogin(result.id);})}>Sign in to your app</button>{login&&<button type="button" onClick={()=>operation(async()=>{await request(`/login/${login}/finish`,'POST');const result=await request<{file?:string;status:string}>(`/login/status?id=${login}`);if(result.file){shot({storage_state:result.file});setLogin('');}else setError(`Sign-in ${result.status}. Finish in the browser, then check again.`);})}>I finished signing in</button>}<button type="button" className="secondary" disabled={busy} onClick={()=>operation(async()=>{const id=await ensureRun();setPreviews(await request<string[]>('/capture/test','POST',{run_id:id,screenshots,format:brief.format}));})}>Test capture</button></div></>}
 {['images','auto'].includes(visuals.source||'')&&<><Field label="Image caption"><input value={caption} onChange={e=>setCaption(e.target.value)} placeholder="Describe the image you’re uploading"/></Field><label className="upload-zone" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();upload(e.dataTransfer.files);}}><Upload/><strong>Drop images or choose files</strong><small>PNG, JPEG or WebP · up to 10 MB each</small><input type="file" multiple accept="image/png,image/jpeg,image/webp" onChange={e=>upload(e.target.files)}/></label><Field label="Or use a local image folder"><input value={typeof visuals.images==='object'?visuals.images?.dir||'':''} onChange={e=>setVisual({images:{dir:e.target.value,describe_images:false}})}/></Field><label className="check"><input type="checkbox" checked={typeof visuals.images==='object'&&!!visuals.images?.describe_images} onChange={e=>setVisual({images:{...(typeof visuals.images==='object'&&visuals.images?visuals.images:{dir:''}),describe_images:e.target.checked}})}/>Let AI describe my images</label><small>This sends your images to your LLM provider.</small></>}
 {['generate','auto'].includes(visuals.source||'')&&<><label className="check"><input type="checkbox" disabled={!providers.data?.openai} checked={!!visuals.generate} onChange={e=>setVisual({generate:e.target.checked?{provider:'openai',style:'',max_images:6}:false})}/>Generate concept images</label>{!providers.data?.openai&&<small>Set OPENAI_API_KEY to enable image generation.</small>}{typeof visuals.generate==='object'&&visuals.generate&&<><Field label="Image style"><input value={visuals.generate.style} onChange={e=>setVisual({generate:{provider:'openai',style:e.target.value,max_images:visuals.generate && typeof visuals.generate==='object'?visuals.generate.max_images:6}})}/></Field><Field label="Maximum images"><input type="number" min={0} max={20} value={visuals.generate.max_images} onChange={e=>setVisual({generate:{provider:'openai',style:visuals.generate && typeof visuals.generate==='object'?visuals.generate.style:'',max_images:+e.target.value}})}/></Field></>}<p className="muted">Generated images are never used for scenes showing your product.</p></>}
 <div className="thumbnails">{previews.map(p=><img key={p} src={fileUrl(runId,p)} alt="Uploaded or captured visual"/>)}</div></section>}
 <div className="form-actions"><span className="muted">Draft saved on this device</span>{step===0&&advanced?<button type="button" disabled={busy} onClick={handleSubmit(()=>setStep(1))}>Continue to visuals<ArrowRight size={16}/></button>:<button type="submit" disabled={busy}>{busy?'Working…':advanced?'Write my script':'Make my video'}<ArrowRight size={16}/></button>}</div></div><aside className="brief-summary"><div className="eyebrow">THE FRAME</div><div className="sample-frame" style={{aspectRatio:(brief.format||'16:9').replace(':','/'),background:brief.brand?.colors?.[1]||'#111312',color:brief.brand?.colors?.[2]||'#f5f3eb'}}><span style={{color:brief.brand?.colors?.[0]||'#bafa42'}}>YOUR STORY, IN MOTION.</span><strong>{brief.features?.[0]||'One clear idea.'}</strong><small>{brief.closing||'Make it memorable.'}</small></div><h3>{brief.duration||60} seconds. Your direction.</h3><p>{brief.level==='high'?'Review the script, shape each scene, then approve the images.':brief.level==='medium'?'Review and edit the script before production begins.':'Your brief goes straight to production.'}</p><div className="summary-line"><span>Voice</span><strong>{brief.voice?.accent} · {brief.voice?.gender}</strong></div><div className="summary-line"><span>Scenes, estimated</span><strong>{(brief.features?.length||1)+3}</strong></div><div className="summary-line"><span>Runs locally</span><strong>On this machine</strong></div></aside></form></>;
}
