import {useEffect, useState} from 'react';
import {useMutation, useQuery, useQueryClient} from '@tanstack/react-query';
import {CheckCircle2, CircleAlert, Play, RefreshCw} from 'lucide-react';
import {request, type Config} from '../api/client';
import {ErrorNote, Field, VoiceFields} from '../components/common';

const providers = ['claude','bedrock','openai','ollama','copilot'] as const;
export function SettingsPage() {
  const queryClient=useQueryClient();
  const settings=useQuery({queryKey:['settings'],queryFn:()=>request<Config>('/settings')});
  const status=useQuery({queryKey:['providers'],queryFn:()=>request<Record<string,any>>('/providers/status')});
  const doctor=useQuery({queryKey:['doctor'],queryFn:()=>request<{name:string;ok:boolean;detail:string}[]>('/doctor')});
  const [form,setForm]=useState<Config|null>(null);const [advanced,setAdvanced]=useState(false);const [testing,setTesting]=useState('');const [result,setResult]=useState('');const [quick,setQuick]=useState(()=>{try{return localStorage.getItem('reelhive-quick-actions')!=='off';}catch{return true;}});
  useEffect(()=>{if(settings.data)setForm(settings.data);},[settings.data]);
  const save=useMutation({mutationFn:(value:Config)=>request<Config>('/settings','PUT',value),onSuccess:value=>{setForm(value);queryClient.setQueryData(['settings'],value);}});
  if(!form)return <p className="muted">Loading settings…</p>;
  const setTier=(tier:'strong'|'fast',value:string)=>setForm({...form,tier_providers:{...form.tier_providers,[tier]:value as any}});
  return <><div className="page-heading"><div><div className="eyebrow">LOCAL CONFIGURATION</div><h1>Settings</h1><p>Models, defaults, and storage. Secrets stay in your environment.</p></div><button disabled={save.isPending} onClick={()=>save.mutate(form)}>Save settings</button></div><ErrorNote error={save.error}/>
   <label className="check"><input type="checkbox" checked={quick} onChange={e=>{setQuick(e.target.checked);try{localStorage.setItem('reelhive-quick-actions',e.target.checked?'on':'off');}catch{/* private mode */}}}/><span><strong>AI quick actions</strong> <small>3-4 suggested edits under the selected beat or scene, from the fast-tier model. Not available when the provider is GitHub Copilot.</small></span></label>
   <div className="settings-grid"><section><div className="section-title"><span>01</span><h2>Providers</h2></div><div className="provider-grid">{providers.map(name=><div className="provider" key={name}><span className={`provider-light ${status.data?.[name]?'ready':''}`}/><strong>{name[0].toUpperCase()+name.slice(1)}</strong><small>{status.data?.[name]?'Ready':'Not configured'}</small><button className="secondary compact" disabled={testing===name} onClick={async()=>{setTesting(name);setResult('');try{const r=await request<{seconds:number}>(`/providers/${name}/test`,'POST');setResult(`${name}: connected in ${r.seconds}s`);}catch(e){setResult(`${name}: ${e instanceof Error?e.message:e}`);}finally{setTesting('');}}}>{testing===name?<RefreshCw className="spin" size={14}/>:<Play size={14}/>}Test</button></div>)}</div>{result&&<p className="notice">{result}</p>}<div className="row"><Field label="Strong tier"><select value={form.tier_providers?.strong||form.provider} onChange={e=>setTier('strong',e.target.value)}>{providers.map(p=><option key={p}>{p}</option>)}</select></Field><Field label="Fast tier"><select value={form.tier_providers?.fast||form.provider} onChange={e=>setTier('fast',e.target.value)}>{providers.map(p=><option key={p}>{p}</option>)}</select></Field></div><label className="check"><input type="checkbox" checked={advanced} onChange={e=>setAdvanced(e.target.checked)}/>Per-agent overrides</label>{advanced&&<div className="node-settings">{['script','scenes','music','critic','fix'].map(node=><Field key={node} label={node}><select value={form.nodes?.[node as keyof typeof form.nodes]||''} onChange={e=>setForm({...form,nodes:{...form.nodes,[node]:e.target.value||undefined} as any})}><option value="">Use tier</option>{providers.map(p=><option key={p}>{p}</option>)}</select></Field>)}</div>}</section>
   <section><div className="section-title"><span>02</span><h2>Defaults</h2></div><div className="row"><Field label="Control level"><select value={form.defaults.level} onChange={e=>setForm({...form,defaults:{...form.defaults,level:e.target.value as any}})}><option>small</option><option>medium</option><option>high</option></select></Field><Field label="Format"><select value={form.defaults.format} onChange={e=>setForm({...form,defaults:{...form.defaults,format:e.target.value as any}})}><option>16:9</option><option>9:16</option><option>1:1</option></select></Field></div><VoiceFields value={form.defaults.voice} onChange={voice=>setForm({...form,defaults:{...form.defaults,voice}})}/><div className="row"><Field label="Music mood"><select value={form.defaults.music_mood||''} onChange={e=>setForm({...form,defaults:{...form.defaults,music_mood:(e.target.value||null) as any}})}><option value="">None</option>{['calm','upbeat','dramatic','inspiring','tech'].map(v=><option key={v}>{v}</option>)}</select></Field><Field label="Credit placement"><select value={form.defaults.credit} onChange={e=>setForm({...form,defaults:{...form.defaults,credit:e.target.value as any}})}><option value="end">End card</option><option value="corner">Corner</option></select></Field></div></section>
   <section><div className="section-title"><span>03</span><h2>Storage & readiness</h2></div><dl className="facts"><div><dt>Runs folder</dt><dd>{status.data?.runs_dir}</dd></div><div><dt>Disk used</dt><dd>{((status.data?.disk_bytes||0)/1024/1024).toFixed(1)} MB</dd></div>{Object.entries(status.data?.versions||{}).map(([name,value])=><div key={name}><dt>{name}</dt><dd>{String(value)}</dd></div>)}</dl><div className="doctor">{doctor.data?.map(check=><div key={check.name}>{check.ok?<CheckCircle2 size={17}/>:<CircleAlert size={17}/>}<span><strong>{check.name}</strong><small>{check.detail}</small></span></div>)}</div></section></div>
  </>;
}
