import {Button, Help} from '../components/Help';
import {Guide} from '../components/Guide';
import {stages} from '../components/help-text';
import {useEffect, useState} from 'react';
import {useMutation, useQuery, useQueryClient} from '@tanstack/react-query';
import {CheckCircle2, CircleAlert, Play, RefreshCw} from 'lucide-react';
import {request, type Config} from '../api/client';
import {ErrorNote, Field, VoiceFields} from '../components/common';

const readinessLabel = (name:string) => ({python:'Local processing',node:'Studio runtime','renderer deps':'Video engine','headless chrome':'Frame creation',ffmpeg:'Audio and video mixing','espeak-ng':'Pronunciation',kokoro:'Narration voice',credit:'Video credit','capture chromium':'App capture',ANTHROPIC_API_KEY:'Writing service credentials',OPENAI_API_KEY:'Image service credentials'}[name] || 'AI service connection');
const providers = ['claude','bedrock','openai','ollama','copilot'] as const;
export function SettingsPage() {
  const queryClient=useQueryClient();
  const settings=useQuery({queryKey:['settings'],queryFn:()=>request<Config>('/settings')});
  const status=useQuery({queryKey:['providers'],queryFn:()=>request<Record<string,any>>('/providers/status')});
  const doctor=useQuery({queryKey:['doctor'],queryFn:()=>request<{name:string;ok:boolean;detail:string}[]>('/doctor')});
  const [saved,setSaved]=useState(false);
  const [form,setForm]=useState<Config|null>(null);const [advanced,setAdvanced]=useState(false);const [testing,setTesting]=useState('');const [result,setResult]=useState('');const [quick,setQuick]=useState(()=>{try{return localStorage.getItem('reelhive-quick-actions')!=='off';}catch{return true;}});
  useEffect(()=>{if(settings.data)setForm(settings.data);},[settings.data]);
  const save=useMutation({mutationFn:(value:Config)=>request<Config>('/settings','PUT',value),onSuccess:value=>{setForm(value);queryClient.setQueryData(['settings'],value);setSaved(true);queryClient.invalidateQueries({queryKey:['doctor']});}});
  if(settings.error)return <ErrorNote error={settings.error}/>;
  if(!form)return <p className="muted">Loading settings…</p>;
  const setTier=(tier:'strong'|'fast',value:string)=>setForm({...form,tier_providers:{...form.tier_providers,[tier]:value as any}});
  return <><Guide title="Choose who helps create your video." next="Connect your AI services, test access, and set defaults for new briefs. Account names appear here so you can choose the right service; production explains each agent’s role."/><div className="page-heading"><div><div className="eyebrow">LOCAL CONFIGURATION</div><h1>Settings</h1><p>Models, defaults, and storage. Secrets stay in your environment.</p></div><Button disabled={save.isPending} onClick={()=>{setSaved(false);save.mutate(form);}}>Save settings</Button></div><ErrorNote error={save.error||status.error||doctor.error}/>{saved&&<p role="status" className="notice">Settings saved. Existing productions keep their original configuration.</p>}
   <label className="check"><input type="checkbox" checked={quick} onChange={e=>{setQuick(e.target.checked);try{localStorage.setItem('reelhive-quick-actions',e.target.checked?'on':'off');}catch{/* private mode */}}}/><span><strong>AI quick actions</strong> <small>3-4 suggested edits under the selected beat or scene, from the fast-tier model. Availability depends on the selected service.</small></span></label><Help label="AI quick actions">The editor agent suggests changes for the saved beat or scene. Suggestions may use service quota; applying one regenerates that part. You can undo its latest change.</Help>
   <div className="settings-grid"><section><div className="section-title"><span>01</span><h2>Providers</h2></div><div className="provider-grid">{providers.map(name=><div className="provider" key={name}><span className={`provider-light ${status.data?.[name]?'ready':''}`}/><strong>{name[0].toUpperCase()+name.slice(1)}</strong><small>{status.data?.[name]?'Credentials found':'Test connection'}</small><Button className="secondary compact" disabled={testing===name} onClick={async()=>{setTesting(name);setResult('');try{const r=await request<{seconds:number}>(`/providers/${name}/test`,'POST');setResult(`${name}: connected in ${r.seconds}s`);}catch(e){setResult(`${name}: ${e instanceof Error?e.message:e}`);}finally{setTesting('');}}}>{testing===name?<RefreshCw className="spin" size={14}/>:<Play size={14}/>}Test</Button></div>)}</div>{result&&<p className="notice">{result}</p>}<div className="row"><Field label="Strong tier"><select value={form.tier_providers?.strong||form.provider} onChange={e=>setTier('strong',e.target.value)}>{providers.map(p=><option key={p}>{p}</option>)}</select></Field><Field label="Fast tier"><select value={form.tier_providers?.fast||form.provider} onChange={e=>setTier('fast',e.target.value)}>{providers.map(p=><option key={p}>{p}</option>)}</select></Field></div><label className="check"><input type="checkbox" checked={advanced} onChange={e=>setAdvanced(e.target.checked)}/>Per-agent overrides</label><Help label="Per-agent overrides">Use a different AI service for one agent. An override takes priority over the strong or fast tier. Leave Use tier to inherit the tier choice.</Help>{advanced&&<div className="node-settings">{['script','scenes','music','critic','fix'].map(node=><Field key={node} label={stages[node]?.label||node}><select value={form.nodes?.[node as keyof typeof form.nodes]||''} onChange={e=>setForm({...form,nodes:{...form.nodes,[node]:e.target.value||undefined} as any})}><option value="">Use tier</option>{providers.map(p=><option key={p}>{p}</option>)}</select></Field>)}</div>}</section>
   <section><div className="section-title"><span>02</span><h2>Defaults</h2></div><div className="row"><Field label="Control level"><select value={form.defaults.level} onChange={e=>setForm({...form,defaults:{...form.defaults,level:e.target.value as any}})}><option>small</option><option>medium</option><option>high</option></select></Field><Field label="Format"><select value={form.defaults.format} onChange={e=>setForm({...form,defaults:{...form.defaults,format:e.target.value as any}})}><option>16:9</option><option>9:16</option><option>1:1</option></select></Field></div><VoiceFields value={form.defaults.voice} onChange={voice=>setForm({...form,defaults:{...form.defaults,voice}})}/><div className="row"><Field label="Music mood"><select value={form.defaults.music_mood||''} onChange={e=>setForm({...form,defaults:{...form.defaults,music_mood:(e.target.value||null) as any}})}><option value="">None</option>{['calm','upbeat','dramatic','inspiring','tech'].map(v=><option key={v}>{v}</option>)}</select></Field><Field label="Credit placement"><select value={form.defaults.credit} onChange={e=>setForm({...form,defaults:{...form.defaults,credit:e.target.value as any}})}><option value="end">End card</option><option value="corner">Corner</option></select></Field></div></section>
   <section><div className="section-title"><span>03</span><h2>Storage & readiness</h2></div><dl className="facts"><div><dt>Runs folder</dt><dd>{status.data?.runs_dir}</dd></div><div><dt>Disk used</dt><dd>{((status.data?.disk_bytes||0)/1024/1024).toFixed(1)} MB</dd></div></dl><div className="doctor">{doctor.data?.map(check=><div key={check.name}>{check.ok?<CheckCircle2 size={17}/>:<CircleAlert size={17}/>}<span><strong>{readinessLabel(check.name)}</strong><small>{check.ok?'Ready':'Needs setup — check the setup guide and restart the studio.'}</small></span></div>)}</div><p className="muted">If a readiness check needs attention, run the setup command from the user guide. Your account credentials stay outside the studio.</p></section></div>
  </>;
}
