/** Product explanations, kept separate from provider and rendering implementation details. */
export const fieldHelp: Record<string, string> = {
  'Control level': 'Small creates a video automatically. Medium asks you to review the script. High also pauses so you can edit scenes and approve their images.',
  'Who is this for?': 'Name the audience and what they already know. The writing agent uses this to choose vocabulary and examples.',
  'What’s the story?': 'Describe the problem, what changes, and why it matters. The writing agent turns this into a spoken story.',
  'Features to cover': 'Add one clear point per row, up to eight. Order them by importance; the quality review checks their coverage.',
  'Closing message': 'Up to 60 characters that must appear exactly at the end. Use one memorable message or invitation.',
  Seconds: 'Choose 15–180 seconds, including the end credit. More features need more speaking time.',
  Format: 'Landscape suits presentations, portrait suits phone feeds, and square suits mixed feeds. This also changes the image dimensions needed.',
  Voice: 'Choose the voice for the spoken narration. Preview it before starting; a scene can have its own voice in High mode.',
  Accent: 'Choose US or UK pronunciation for the narration.',
  Speed: '1 is normal speed. Values from 0.8 to 1.2 slow down or speed up the spoken narration and affect scene timing.',
  Tone: 'Describe how the narrator should sound, such as friendly and practical or confident and direct.',
  Pacing: 'Guide the rhythm of the story: slow gives ideas room; fast moves briskly. This is separate from voice speed.',
  Theme: 'Choose the video’s visual style. Brand uses your palette; this does not change the studio’s light or dark appearance.',
  'CTA URL': 'An optional address shown with the closing invitation. CTA means call to action: what viewers should do next.',
  'Brand colors': 'Accent highlights important details; background fills the frame; text is the reading color. Choose colors with strong contrast.',
  'Music mood': 'Guide the music agent toward a mood. The sample lets you hear a track before production.',
  'Music volume': 'Set the music level from 0 (silent) to 1 (full). The final mix lowers music while the narrator speaks.',
  'Music track': 'Choose a specific local track, or let the music agent pick one that suits your story.',
  'Made with ReelHive credit': 'End card adds a short credit at the end; Corner keeps a small credit badge over the video.',
  'Credit placement': 'End card adds a short credit at the end; Corner keeps a small credit badge over the video.',
  'Visual source': 'None uses typography. Screenshots captures an app. Images uses your files. Generate creates concept art. Auto tries the sources you configure, then falls back to text.',
  'App URL': 'The address of the app to show in the video. It must be reachable on this computer; start your app first.',
  Routes: 'One page path per line, such as /dashboard. Leave empty to discover up to ten pages on the same site.',
  'Mask selectors': 'CSS selectors identify private page elements to black out before capture, such as .email or [data-secret]. Always inspect a test capture.',
  Frame: 'Show captures inside a browser frame, a phone frame, or without a decorative frame.',
  'Image caption': 'Describe what the uploaded image shows. The scene agent uses captions to choose suitable pictures.',
  'Or use a local image folder': 'An existing folder on this computer. Filenames and captions help match images to scenes; use clear, descriptive names.',
  'Image style': 'Describe a consistent look for generated concept art. It never generates a fake screenshot of your product.',
  'Maximum images': 'A per-run limit on generation attempts, including failed attempts. Generation can incur image-provider charges.',
  'Regeneration note': 'Tell the agent what to change. Regeneration replaces the saved version; save or approve your manual edits first when you want to keep them.',
  Template: 'A scene layout: opening hook, problem, feature card, statistic, bullets, image, moving screenshot, or closing invitation. Switching layouts may shorten or replace text fields.',
  'Duration override': 'Optional seconds for this scene. Leave blank for automatic timing. A short override may not fit the narration and can fail quality review.',
  Headline: 'The main text displayed in this scene. Keep it short enough to read at a glance.',
  'Supporting text': 'Secondary on-screen text. It should support the headline rather than repeat the entire narration.',
  Bullets: 'One short point per line. Keep the list readable at the selected video size.',
  Narration: 'The exact words spoken in this scene. Saving changed narration creates new voice audio and recalculates timing.',
  'Visual kind': 'Product UI uses real screenshots or supplied images. Concept can use artwork. None creates a text-only scene. Changing this resets image approval.',
  'Image or route': 'For product UI, enter a page route. For concept art, enter a description. A changed request must be saved and its new image approved.',
  'Strong tier': 'Choose the AI service used for writing, quality review, and repairs. Its model names and credentials must already be configured.',
  'Fast tier': 'Choose the AI service used for scene design, music selection, and suggested edits. Its model names and credentials must already be configured.',
  'Writing agent': 'Override the writing agent’s service, or inherit its tier selection.',
  'Scene agent': 'Override the scene agent’s service, or inherit its tier selection.',
  'Music agent': 'Override the music agent’s service, or inherit its tier selection.',
  'Review agent': 'Override the review agent’s service, or inherit its tier selection.',
  'Repair agent': 'Override the repair agent’s service, or inherit its tier selection.',
};

export function actionHelp(label: string): string | undefined {
  const actions: [RegExp, string][] = [
    [/^Export brief file$/, 'Download this brief as a reusable text file. It contains settings and paths, not copies of your images or login session.'],
    [/^Preview voice$/, 'Play a short local voice sample with the current settings. The first preview may take longer while voice files load.'],
    [/^Sign in to your app$/, 'Open a separate browser to sign in yourself. Your saved session is kept privately in this run for screenshots.'],
    [/^I finished signing in$/, 'Save the signed-in browser session, then use Test capture to check the pages and privacy masks.'],
    [/^Test capture$/, 'Capture the configured pages now without starting video production. Review the results for private information and layout problems.'],
    [/^Regenerate$/, 'Ask the writing agent to replace the saved script using your note. Unsaved manual edits are not included.'],
    [/^Regenerate scene$/, 'Ask the scene agent to replace this scene using your note. Save manual edits first; check the new image before rendering.'],
    [/^Save scenes$/, 'Save all scene edits and image approvals. Changed narration or visual requests may take time to prepare; wait for the editor to return.'],
    [/^Approve and continue$/, 'Save the visible script and start preparing scenes, voice, visuals, and music. High mode pauses again for scene review.'],
    [/^Approve all and render$/, 'Continue with the saved scenes through quality review and final video creation. Save edits and approve every resolved image first.'],
    [/^Cancel at next node$/, 'Request a stop after the current stage reaches a safe boundary. This may take time. Completed stages are kept for resume.'],
    [/^Resume from checkpoint$/, 'Continue from saved progress. Fix any reported setup or service problem first. Some interrupted work may need to run again.'],
    [/^Reveal folder$/, 'Open this production’s files in your computer’s file manager.'],
    [/^Duplicate as new brief$/, 'Copy these brief settings into the new-video form. This does not copy media files; check referenced paths before starting.'],
    [/^Delete run$/, 'Permanently remove this run and its local files after confirmation. Download anything you need first; active runs must stop before deletion.'],
    [/^Download video$/, 'Download the completed video file to your browser’s download folder.'],
    [/^Test$/, 'Check this service with a small live request. It may use paid account quota. A successful test confirms access for the configured model.'],
    [/^Save settings$/, 'Save non-secret defaults and service choices for new productions. Existing runs keep their saved configuration.'],
    [/^More ideas$/, 'Ask the editor agent for fresh suggestions for this saved beat or scene. This may use your AI service quota.'],
    [/^Undo last change$/, 'Restore the saved version from before the last suggested edit. This is not a general history of every manual edit.'],
    [/^Move feature/, 'Change the priority order of the points the writing agent should cover.'],
    [/^Remove feature/, 'Remove this point from the brief before generation. At least one feature must remain.'],
  ];
  return actions.find(([pattern]) => pattern.test(label))?.[1];
}

export const stages: Record<string, {label: string; doing: string; next: string}> = {
  script: {label: 'Writing agent', doing: 'The writing agent is drafting the spoken story from your brief.', next: 'Next, review the script or let your chosen control level continue automatically.'},
  scenes: {label: 'Scene agent', doing: 'The scene agent is choosing layouts and on-screen text.', next: 'Next, your visuals, voice, and music come together.'},
  visuals: {label: 'Visual preparation', doing: 'Your requested images and app captures are being prepared.', next: 'Next, check the resolved images when scene review opens.'},
  narrate: {label: 'Narration', doing: 'The narrator is turning the script into spoken audio.', next: 'Next, scene timing is adjusted to fit the recorded voice.'},
  music: {label: 'Music agent', doing: 'The music agent is selecting a background track for your story.', next: 'Next, the track joins your narration in the final mix.'},
  timing: {label: 'Scene timing', doing: 'Scene lengths are being matched to the voice and target duration.', next: 'Next, the video is reviewed for timing, readability, and coverage.'},
  critic: {label: 'Quality review', doing: 'The review agent is checking your story, timing, and visual choices.', next: 'If changes are needed, the repair agent will make a pass before the final check.'},
  fix: {label: 'Repair agent', doing: 'The repair agent is improving scenes that did not pass review.', next: 'Next, the updated scenes are checked again.'},
  recheck: {label: 'Final checks', doing: 'The revised scenes are being checked before video creation.', next: 'If they pass, the final video can be created.'},
  render: {label: 'Video creation', doing: 'Your scenes are being turned into a video with voice and music.', next: 'Next, watch the finished video and download your MP4.'},
};
