import {readFileSync, writeFileSync} from 'node:fs';
import {jsonSchemaToZod} from 'json-schema-to-zod';
const schema = JSON.parse(readFileSync('ui/src/schemas/brief.json', 'utf8'));
writeFileSync('ui/src/schemas/brief.ts', '// Generated by scripts/generate_ui.py.\nimport {z} from "zod";\nexport const briefSchema = ' + jsonSchemaToZod(schema) + ';\n');
